version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "mambaforge-23.11"

conda:
  environment: ci/requirements/docs.yml

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false

formats: []

python:
  install:
    - method: pip
      path: .
