name: climpred-docs-notebooks
channels:
  - conda-forge
dependencies:
  - python>=3.7
  - xarray>=0.19.0
  - dask-core>=2021.10.0
  - cftime>=1.5.0
  - xskillscore>=0.0.20
  - cf_xarray>=0.6.0
  - xesmf
  - esmpy
  - pydap
  - matplotlib-base
  - nc-time-axis>=1.4.0
  - netcdf4==1.5.1  # see https://github.com/pydata/xarray/issues/4925
  - toolz
  - xrft
  - esmtools>=1.1.3
  - xclim!=0.30.0
  - bias_correction>=0.4
  - pip
  - pip:
    - git+https://github.com/pangeo-data/climpred.git  # latest climpred version
    - nb_black
