name: Linting

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  linting:
    name: "pre-commit hooks"
    runs-on: ubuntu-latest
    if: github.repository == 'pangeo-data/climpred'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.3
