---
name: binder PR link

on:
  pull_request:
    types: [opened]


jobs:
  comment_PR_link_binder:
    runs-on: ubuntu-latest
    steps:
      - name: Comment PR
        uses: mshick/add-pr-comment@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: >-
            Checkout your PR on
            [![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/pangeo-data/climpred/${{github.head_ref}}?urlpath=lab%2Ftree%2Fdocs%2Fsource%2Fquick-start.ipynb).
            Open the console and `pip install -e .` before using the notebooks to use `climpred` from this PR.
